#!/bin/sh
VERSION=$(cat ./VERSION)
NAME="mazurov-slides-${VERSION}.pdf"

SOURCE="./build/mazurov-ferrara2014.pdf"
TARGET_WWW="/afs/cern.ch/user/a/amazurov/www/${NAME}"
TARGET_LOCAL="./build/${NAME}"
cp $SOURCE $TARGET_LOCAL
echo "File '$SOURCE' copied to '$TARGET_LOCAL'"
cp $SOURCE $TARGET_WWW
echo "File '$SOURCE' copied to '$TARGET_WWW'"
echo "Url: http://cern.ch/amazurov/${NAME}"